# \u4F5C\u4E1A1 CDC \u91C7\u96C6\u914D\u7F6E
# \u6240\u6709\u503C\u90FD\u53EF\u7528\u547D\u4EE4\u884C\u8986\u76D6\uFF1A--key value

# ==================== \u4F5C\u4E1A ====================
job.parallelism = 4

# =================== Checkpoint ==============
# checkpoint \u5468\u671F 1min
checkpoint.interval.ms = 60000
# checkpoint \u5B58\u50A8\u4F4D\u7F6E
checkpoint.dir = hdfs://hadoop1:9000/checkpoint/cdc
# checkpoint \u8D85\u65F6\u65F6\u95F4 3 min
checkpoint.timeout.ms = 180000
# \u5141\u8BB8checkpoint\u8FDE\u63A5\u5931\u8D25\u7684\u6B21\u6570
checkpoint.failure.number.tolerable = 10

# ==================== MySQL \u6E90 ====================
mysql.hostname = hadoop1
mysql.port = 3306
mysql.cdc.username = root
mysql.cdc.password = TMcode@0204

# ==================== CDC ====================
# \u6B63\u5219\u4E00\u6B21\u5339\u914D 10 \u4E2A\u5E93 / 5 \u4E2A\u65E7\u5E93\uFF08\u89C1\u6587\u6863 2.1\uFF09
cdc.lot.database.pattern = mes_(old|new)_.*
cdc.barcode.database.pattern = mes_old_.*
cdc.order.database.pattern = mes_(old|new)_.*

# server-id \u533A\u95F4\u5FC5\u987B\u4E92\u4E0D\u91CD\u53E0\uFF0C\u4E14\u533A\u95F4\u957F\u5EA6 >= \u8BE5 source \u7684\u5E76\u884C\u5EA6\u3002
# \u51B2\u7A81\u65F6\u7684\u62A5\u9519\u662F\uFF1AA slave with the same server_uuid/server_id as this slave has connected to the master
cdc.lot.server.id = 5400-5409
cdc.barcode.server.id = 5410-5419
cdc.order.server.id = 5420-5429

# initial = \u5168\u91CF snapshot + \u589E\u91CF binlog\u3002\u5F00\u53D1\u671F\u522B\u7528 latest-offset\uFF1A
# \u6CA1\u6709\u65B0\u6570\u636E\u5199\u5165\u65F6\u4F1A\u770B\u5230\u4F5C\u4E1A\u5728\u8DD1\u4F46\u4E00\u6761\u6570\u636E\u4E5F\u6CA1\u6709\uFF0C\u767D\u6392\u67E5\u534A\u5929\u3002
cdc.startup.mode = initial

# \u5168\u91CF\u9636\u6BB5\u5206\u7247\u5927\u5C0F\u3002\u8C03\u5927\u5BB9\u6613 OOM\uFF0C\u8C03\u5C0F\u4F1A\u4EA7\u751F\u8FC7\u591A split,\u9ED8\u8BA48090\u3002
cdc.snapshot.chunk.size = 8096

# \u5FC5\u987B\u4E0E MySQL \u7684 time_zone \u4E00\u81F4\uFF0C\u5426\u5219 DATETIME \u504F\u79FB 8 \u5C0F\u65F6
cdc.server.timezone = Asia/Shanghai

# ==================== Kafka Sink ====================
kafka.bootstrap.servers = hadoop1:9092,hadoop2:9092,hadoop3:9092
kafka.ods.report.topic = ods-mes-report
kafka.ods.order.topic = ods-mes-order
